
import React, { useState, useEffect } from 'react';
import { UserAccount, HistoryItem } from '../types';
import { jsPDF } from 'jspdf';

interface AccountProfileProps {
  account: UserAccount;
  onUpdateAccount: (account: UserAccount) => void;
  onViewHistory: (item: HistoryItem) => void;
  onLogout: () => void;
}

const AccountProfile: React.FC<AccountProfileProps> = ({ account, onUpdateAccount, onViewHistory, onLogout }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [isSyncing, setIsSyncing] = useState(false);
  const [tempAccount, setTempAccount] = useState(account);
  const [isGeneratingDoc, setIsGeneratingDoc] = useState(false);

  const handleSave = () => {
    onUpdateAccount(tempAccount);
    setIsEditing(false);
  };

  const syncNow = async () => {
    setIsSyncing(true);
    await new Promise(r => setTimeout(r, 1200));
    onUpdateAccount({ ...account, lastDriveSync: new Date().toLocaleString() });
    setIsSyncing(false);
  };

  const handleDownloadDocs = () => {
    setIsGeneratingDoc(true);
    setTimeout(() => {
      const doc = new jsPDF();
      
      // Header
      doc.setFillColor(15, 23, 42); // slate-900
      doc.rect(0, 0, 210, 40, 'F');
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.text("Guardify Auditor", 20, 25);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text("System Architecture & Build Specification", 20, 32);

      // Content Colors
      doc.setTextColor(30, 41, 59); // slate-800

      let yPos = 60;

      // Section 1
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("1. Technical Stack Overview", 20, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text([
        "The application is engineered as a high-performance Progressive Web App (PWA) leveraging",
        "modern browser capabilities for zero-latency analysis.",
        "",
        "• Core Runtime: React 19 (release candidate) using ES Modules",
        "• Type Safety: TypeScript 5.x strict mode implementation",
        "• Styling Engine: Tailwind CSS (Utility-first architecture)",
        "• Intelligence Layer: Google Gemini 3.0 Pro & Flash models",
        "• State Persistence: LocalStorage & IndexedDB (Client-side only)"
      ], 25, yPos);
      
      yPos += 50;

      // Section 2
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("2. Application Architecture", 20, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text([
        "Guardify operates on a 'Client-Sovereign' architecture. All privacy analysis logic",
        "is executed within the browser's secure context context, ensuring source code",
        "never leaves the local session except for ephemeral API inference.",
        "",
        "Key Modules:",
        "• AuditDashboard: Orchestrates multi-vector policy cross-verification.",
        "• GitIntegration: Simulates CI/CD pipeline hooks via Diff analysis.",
        "• ServiceWorker: Manages offline asset caching and installability.",
        "• GeminiService: Handles cryptographic signing of audit logs."
      ], 25, yPos);

      yPos += 55;

      // Section 3
      doc.setFontSize(14);
      doc.setFont("helvetica", "bold");
      doc.text("3. Build & Deployment Pipeline", 20, yPos);
      yPos += 10;
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.text([
        "The build system bypasses traditional bundlers (Webpack/Vite) in favor of native",
        "ESM imports via <script type='importmap'>, reducing build complexity and",
        "enabling instant runtime updates.",
        "",
        "Deployment Requirements:",
        "• TLS 1.3 Encryption (Required for Service Workers)",
        "• Content Security Policy (CSP) allowing 'esm.sh' CDN",
        "• manifest.json for PWA installation criteria"
      ], 25, yPos);

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(100, 116, 139);
      doc.text(`Generated by Guardify Engine | ${new Date().toLocaleString()}`, 20, 280);

      doc.save("Guardify_System_Architecture.pdf");
      setIsGeneratingDoc(false);
    }, 1000);
  };

  const avgScore = account.history.length > 0 
    ? Math.round(account.history.reduce((acc, curr) => acc + curr.result.overallScore, 0) / account.history.length)
    : 0;

  return (
    <div className="space-y-8 animate-in fade-in duration-500 max-w-7xl mx-auto">
      <header className="flex items-end justify-between border-b border-slate-200 pb-6">
        <div>
          <h2 className="text-3xl font-bold text-slate-900 tracking-tight">Enterprise Configuration</h2>
          <p className="text-slate-500 text-sm font-medium mt-1">Manage workspace preferences and historical audit logs.</p>
        </div>
        <div className="flex gap-3">
           <button 
             onClick={() => setIsEditing(!isEditing)}
             className="px-5 py-2.5 bg-white border border-slate-300 rounded-lg text-sm font-bold text-slate-700 hover:bg-slate-50 transition-all shadow-sm"
           >
             {isEditing ? 'Cancel' : 'Edit Profile'}
           </button>
           {isEditing && (
             <button onClick={handleSave} className="px-5 py-2.5 bg-blue-700 text-white rounded-lg text-sm font-bold shadow-md hover:bg-blue-800 transition-all">
                Save Changes
             </button>
           )}
        </div>
      </header>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left Column: Profile & Stats */}
        <div className="space-y-6">
          <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
            <div className="flex flex-col items-center text-center">
              <div className="w-20 h-20 rounded-lg bg-slate-900 flex items-center justify-center text-white text-2xl font-bold mb-4 shadow-md">
                {account.name.charAt(0)}
              </div>
              
              {isEditing ? (
                <div className="w-full space-y-3 text-left">
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-slate-500 uppercase">Full Name</label>
                    <input
                      type="text"
                      value={tempAccount.name}
                      onChange={(e) => setTempAccount({...tempAccount, name: e.target.value})}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-sm font-medium focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none"
                    />
                  </div>
                  <div className="space-y-1">
                    <label className="text-xs font-bold text-slate-500 uppercase">Organization</label>
                    <input
                      type="text"
                      value={tempAccount.company}
                      onChange={(e) => setTempAccount({...tempAccount, company: e.target.value})}
                      className="w-full px-3 py-2 bg-slate-50 border border-slate-300 rounded-lg text-sm font-medium focus:ring-2 focus:ring-blue-500/20 focus:border-blue-500 outline-none"
                    />
                  </div>
                </div>
              ) : (
                <>
                  <h3 className="text-lg font-bold text-slate-900">{account.name}</h3>
                  <p className="text-xs font-bold text-slate-500 uppercase tracking-wide mt-1">{account.company}</p>
                  <div className="mt-2 px-3 py-1 bg-slate-100 rounded text-[10px] font-bold text-slate-600 border border-slate-200">
                    {account.role}
                  </div>
                  
                  <button
                    onClick={onLogout}
                    className="mt-4 w-full py-2 bg-white border border-rose-200 rounded-lg text-xs font-bold text-rose-600 hover:bg-rose-50 transition-all flex items-center justify-center gap-2 shadow-sm"
                  >
                    <i className="fa-solid fa-arrow-right-from-bracket"></i>
                    Sign Out
                  </button>
                </>
              )}
            </div>

            <div className="mt-8 grid grid-cols-2 gap-3">
               <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 text-center">
                  <p className="text-2xl font-bold text-slate-900 leading-none">{account.history.length}</p>
                  <p className="text-[10px] font-bold text-slate-500 uppercase mt-2">Total Audits</p>
               </div>
               <div className="p-4 bg-slate-50 rounded-lg border border-slate-200 text-center">
                  <p className="text-2xl font-bold text-blue-700 leading-none">{avgScore}%</p>
                  <p className="text-[10px] font-bold text-slate-500 uppercase mt-2">Avg. Score</p>
               </div>
            </div>
          </div>

          <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
            <div className="flex items-center gap-3 mb-4">
              <div className="w-9 h-9 rounded-lg bg-indigo-50 flex items-center justify-center text-indigo-700 border border-indigo-100">
                <i className="fa-solid fa-book-open"></i>
              </div>
              <div>
                <h4 className="text-sm font-bold text-slate-900">Technical Docs</h4>
                <p className="text-[10px] text-slate-500 font-medium">Architecture Specification</p>
              </div>
            </div>
            <p className="text-xs text-slate-500 leading-relaxed mb-4">
              Download the official engineering reference manual detailing the build process and system architecture.
            </p>
            <button 
              onClick={handleDownloadDocs}
              disabled={isGeneratingDoc}
              className="w-full py-3 bg-white text-slate-700 border border-slate-200 rounded-lg text-xs font-bold hover:bg-slate-50 transition-all flex items-center justify-center gap-2 shadow-sm"
            >
              {isGeneratingDoc ? <i className="fa-solid fa-spinner fa-spin"></i> : <i className="fa-solid fa-file-pdf text-rose-600"></i>}
              {isGeneratingDoc ? 'Generating PDF...' : 'Download Architecture PDF'}
            </button>
          </div>

          <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
             <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-lg bg-emerald-50 flex items-center justify-center text-emerald-700 border border-emerald-100">
                    <i className="fa-brands fa-google-drive"></i>
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-slate-900">Cloud Storage</h4>
                    <p className="text-[10px] text-slate-500 font-medium">Remote Backup Status</p>
                  </div>
                </div>
                <div 
                  className={`w-10 h-5 rounded-full transition-colors relative cursor-pointer border ${account.isDriveConnected ? 'bg-emerald-600 border-emerald-600' : 'bg-slate-200 border-slate-300'}`} 
                  onClick={() => onUpdateAccount({...account, isDriveConnected: !account.isDriveConnected})}
                >
                   <div className={`absolute top-0.5 w-3.5 h-3.5 bg-white rounded-full transition-all shadow-sm ${account.isDriveConnected ? 'left-[22px]' : 'left-0.5'}`}></div>
                </div>
             </div>
             
             {account.isDriveConnected ? (
               <div className="space-y-3 animate-in fade-in duration-300">
                  <div className="flex items-center gap-2 text-[10px] font-bold text-emerald-700 bg-emerald-50 p-2 rounded border border-emerald-100">
                    <i className="fa-solid fa-check-circle"></i>
                    Connection Established
                  </div>
                  <button 
                    onClick={syncNow}
                    disabled={isSyncing}
                    className="w-full py-3 bg-slate-900 text-white rounded-lg text-xs font-bold hover:bg-slate-800 transition-all flex items-center justify-center gap-2"
                  >
                    {isSyncing ? <i className="fa-solid fa-circle-notch fa-spin"></i> : <i className="fa-solid fa-rotate"></i>}
                    {isSyncing ? 'Syncing...' : 'Force Sync Now'}
                  </button>
                  <p className="text-[10px] text-center text-slate-400 font-medium">Last successful sync: {account.lastDriveSync || 'Never'}</p>
               </div>
             ) : (
               <p className="text-xs text-slate-500 leading-relaxed border-t border-slate-100 pt-3">
                 Connect corporate Google Drive to enable automated compliance report archiving and audit trails.
               </p>
             )}
          </div>

          {/* Preferences Section */}
          <div className="bg-white border border-slate-200 p-6 rounded-xl shadow-sm">
             <div className="flex items-center gap-3 mb-6">
               <div className="w-9 h-9 rounded-lg bg-slate-100 flex items-center justify-center text-slate-600 border border-slate-200">
                 <i className="fa-solid fa-sliders"></i>
               </div>
               <div>
                 <h4 className="text-sm font-bold text-slate-900">System Preferences</h4>
                 <p className="text-[10px] text-slate-500 font-medium">Global Configuration</p>
               </div>
             </div>

             <div className="space-y-4">
               {/* Theme Toggle */}
               <div className="flex items-center justify-between">
                 <div>
                   <p className="text-xs font-bold text-slate-700">Interface Theme</p>
                   <p className="text-[10px] text-slate-400">Select workspace appearance</p>
                 </div>
                 <div className="flex bg-slate-100 p-1 rounded-lg border border-slate-200">
                   {(['light', 'system', 'dark'] as const).map((theme) => (
                     <button
                       key={theme}
                       onClick={() => {
                         const currentPreferences = account.preferences || { theme: 'system', notifications: true, autoSyncDrive: false };
                         onUpdateAccount({
                           ...account,
                           preferences: { ...currentPreferences, theme }
                         });
                       }}
                       className={`px-3 py-1 rounded-md text-[10px] font-bold transition-all ${
                         (account.preferences?.theme || 'system') === theme
                           ? 'bg-white text-slate-900 shadow-sm'
                           : 'text-slate-400 hover:text-slate-600'
                       }`}
                     >
                       {theme.charAt(0).toUpperCase() + theme.slice(1)}
                     </button>
                   ))}
                 </div>
               </div>

               {/* Notifications Toggle */}
               <div className="flex items-center justify-between border-t border-slate-50 pt-4">
                 <div>
                   <p className="text-xs font-bold text-slate-700">Audit Notifications</p>
                   <p className="text-[10px] text-slate-400">Email alerts for critical risks</p>
                 </div>
                 <div 
                   onClick={() => {
                     const currentPreferences = account.preferences || { theme: 'system', notifications: true, autoSyncDrive: false };
                     onUpdateAccount({
                       ...account,
                       preferences: { ...currentPreferences, notifications: !currentPreferences.notifications }
                     });
                   }}
                   className={`w-10 h-5 rounded-full transition-colors relative cursor-pointer border ${
                     (account.preferences?.notifications ?? true) ? 'bg-blue-600 border-blue-600' : 'bg-slate-200 border-slate-300'
                   }`}
                 >
                   <div className={`absolute top-0.5 w-3.5 h-3.5 bg-white rounded-full transition-all shadow-sm ${
                     (account.preferences?.notifications ?? true) ? 'left-[22px]' : 'left-0.5'
                   }`}></div>
                 </div>
               </div>

               {/* Auto-Sync Toggle */}
               <div className="flex items-center justify-between border-t border-slate-50 pt-4">
                 <div>
                   <p className="text-xs font-bold text-slate-700">Auto-Sync Drive</p>
                   <p className="text-[10px] text-slate-400">Backup reports automatically</p>
                 </div>
                 <div 
                   onClick={() => {
                     const currentPreferences = account.preferences || { theme: 'system', notifications: true, autoSyncDrive: false };
                     onUpdateAccount({
                       ...account,
                       preferences: { ...currentPreferences, autoSyncDrive: !currentPreferences.autoSyncDrive }
                     });
                   }}
                   className={`w-10 h-5 rounded-full transition-colors relative cursor-pointer border ${
                     (account.preferences?.autoSyncDrive ?? false) ? 'bg-blue-600 border-blue-600' : 'bg-slate-200 border-slate-300'
                   }`}
                 >
                   <div className={`absolute top-0.5 w-3.5 h-3.5 bg-white rounded-full transition-all shadow-sm ${
                     (account.preferences?.autoSyncDrive ?? false) ? 'left-[22px]' : 'left-0.5'
                   }`}></div>
                 </div>
               </div>
             </div>
          </div>
        </div>

        {/* Right Column: History */}
        <div className="lg:col-span-2">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wide">System of Record</h3>
            <span className="text-[10px] font-bold text-slate-500 bg-slate-100 px-2 py-1 rounded border border-slate-200">
              Immutable Log
            </span>
          </div>

          {account.history.length === 0 ? (
            <div className="bg-slate-50 border border-slate-200 border-dashed rounded-xl p-16 flex flex-col items-center justify-center">
               <div className="w-12 h-12 bg-white rounded-lg flex items-center justify-center mb-4 border border-slate-200 shadow-sm">
                  <i className="fa-solid fa-clipboard-list text-slate-400"></i>
               </div>
               <p className="text-slate-900 font-bold text-sm">No Audit Records Found</p>
               <p className="text-slate-500 text-xs mt-1">Execute a compliance scan to generate logs.</p>
            </div>
          ) : (
            <div className="bg-white border border-slate-200 rounded-xl overflow-hidden shadow-sm">
              <table className="w-full text-left">
                <thead className="bg-slate-50 border-b border-slate-200">
                  <tr>
                    <th className="px-5 py-3 text-[10px] font-bold text-slate-500 uppercase tracking-wider">Timestamp</th>
                    <th className="px-5 py-3 text-[10px] font-bold text-slate-500 uppercase tracking-wider">Context</th>
                    <th className="px-5 py-3 text-[10px] font-bold text-slate-500 uppercase tracking-wider">Result</th>
                    <th className="px-5 py-3 text-[10px] font-bold text-slate-500 uppercase tracking-wider text-right">Action</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {account.history.map((item) => (
                    <tr 
                      key={item.id} 
                      className="hover:bg-slate-50/80 transition-colors cursor-pointer group"
                      onClick={() => onViewHistory(item)}
                    >
                      <td className="px-5 py-4">
                        <div className="flex flex-col">
                          <span className="text-xs font-bold text-slate-700">{item.timestamp.split(',')[0]}</span>
                          <span className="text-[10px] text-slate-400 font-medium">{item.timestamp.split(',')[1]}</span>
                        </div>
                      </td>
                      <td className="px-5 py-4">
                        <div className="max-w-[200px] truncate">
                           <p className="text-xs font-medium text-slate-900 truncate">{item.policyPreview}</p>
                           <p className="text-[10px] text-slate-400 mt-0.5">{item.metadata?.engineSignature || 'Standard Analysis'}</p>
                        </div>
                      </td>
                      <td className="px-5 py-4">
                        <span className={`inline-flex items-center px-2 py-0.5 rounded text-[10px] font-bold uppercase border ${
                          item.result.status === 'Compliant' ? 'bg-emerald-50 text-emerald-700 border-emerald-200' :
                          item.result.status === 'Partial' ? 'bg-amber-50 text-amber-700 border-amber-200' :
                          'bg-rose-50 text-rose-700 border-rose-200'
                        }`}>
                          {item.result.status} ({item.result.overallScore}%)
                        </span>
                      </td>
                      <td className="px-5 py-4 text-right">
                        <i className="fa-solid fa-chevron-right text-xs text-slate-300 group-hover:text-slate-600 transition-colors"></i>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AccountProfile;
